name: Second Chance CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: SecondChance
  AZURE_WEBAPP_PACKAGE_PATH: "publish"
  DOTNET_VERSION: "8.x"
  SOLUTION_PATH: "SecondChance.sln"
  API_PROJECT_PATH: "./SecondChance/SecondChance.csproj"
  PUBLISH_DIR: "publish"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --filter "Category=Unit|FullyQualifiedName~.Unit."
      
      - name: Run Integration Tests
        run: dotnet test --configuration Release --no-build --filter "Category=Integration|FullyQualifiedName~.Integration."
      
      - name: Publish
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --output ${{ env.PUBLISH_DIR }}
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: webapp
          path: ${{ env.PUBLISH_DIR }}
